core/urls.py
from django.urls import path
from .views import (
    MovieList,
    MovieDetail,
    CreateVote,
    UpdateVote,
    MovieImageUpload,
    TopMovies
)

app_name = 'core'

urlpatterns = [
    path(
        'movies',
        MovieList.as_view(),
        name='MovieList'
    ),
    path(
        'movie/<int:pk>',
        MovieDetail.as_view(),
        name='MovieDetail'
    ),
    path(
        'movie/<int:movie_id>/vote',
        CreateVote.as_view(),
        name='CreateVote'
    ),
    path(
        'movie/<int:movie_id>/vote/<int:pk>',
        UpdateVote.as_view(),
        name='UpdateVote'
    ),
    path(
        'movie/<int:movie_id>/image/upload',
        MovieImageUpload.as_view(),
        name='MovieImageUpload'
    ),
    path(
        'movie/top',
        TopMovies.as_view(),
        name="TopMovies"
    ),
]

myMDB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import core.urls
import user.urls

# Development setting for specifying upload path
MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
] + MEDIA_FILE_PATHS

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum
from uuid import uuid4


#==========================================================
# Custom Model Managers
#==========================================================
class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def get_top_ten(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum('vote__value'))
        # For filtering out movies with no votes from being in the top 10
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


class PersonManager(models.Manager):

    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )


#==========================================================
# Models
#==========================================================

# Helper function(s)
def movie_directory_path_with_uuid(instance, file_name):
    return "{}/{}".format(instance.movie_id, uuid4())


class Movie(models.Model):

    # Choices
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),
    )

    # Model fields
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True
    )
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True
    )
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True
    )

    # Custom Manager class
    objects = MovieManager()

    # Meta class attributes
    class Meta:
        ordering = (
            '-year',
            'title',
        )

    # Human friendly obj representation
    def __str__(self):
        return "{} ({})".format(
            self.title,
            self.year
        )


class MovieImage(models.Model):
    image = models.ImageField(
        upload_to=movie_directory_path_with_uuid
    )
    uploaded = models.DateTimeField(auto_now=True)
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )


class Person(models.Model):

    # Model fields
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    # Custom Manager class
    objects = PersonManager()

    # Meta class attributes
    class Meta:
        ordering = (
            'last_name',
            'first_name',
        )

    # Human friendly obj representation
    def __str__(self):
        if self.died:
            return "{}, {} ({}-{})".format(
                self.last_name,
                self.first_name,
                self.born,
                self.died
            )
        else:
            return "{}, {} ({})".format(
                self.last_name,
                self.first_name,
                self.born,
            )


class Role(models.Model):
    movie = models.ForeignKey(to='Movie', on_delete=models.DO_NOTHING)
    person = models.ForeignKey(to='Person', on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    class Meta:
        unique_together = (
            'movie',
            'person',
            'name',
        )

    def __str__(self):
        return "{} {} {}".format(
            self.movie_id,
            self.person_id,
            self.name
        )


class Vote(models.Model):
    # Constants
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "👍",),
        (DOWN, "👎",),
    )

    # Model fields
    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(to=Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    # Custom Manager class
    objects = VoteManager()

    # Meta class attributes
    class Meta:
        unique_together = (
            'user', 'movie'
        )

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from core.models import Vote, Movie, MovieImage


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES
    )

    class Meta:
        model = Vote
        fields = (
            'value',
            'user',
            'movie',
        )


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    class Meta:
        model = MovieImage
        fields = (
            'image',
            'user',
            'movie',
        )

core/views.py
import django
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.core.cache import cache
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from core.models import Movie, Person, Vote
from core.forms import VoteForm, MovieImageForm
from core.mixins import CachePageVaryOnCookieMixin


class MovieList(ListView, CachePageVaryOnCookieMixin):
    """
    Now when MovieList gets a request routed to it,
    cache_page will check whether it has already been cached.
    If it has been cached, Django will return the cached
    response without doing any more work. If it hasn't been
    cached, our regular MovieList view will create a new response.
    The new response will have a VARY cookie header added and
    then get cached.
    """
    model = Movie
    paginate_by = 10


class TopMovies(ListView):
    template_name = 'core/top_movies_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return  cached_qs
        qs = Movie.objects.get_top_ten(limit=limit)
        cache.set(key, qs)
        return qs


class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_score()

    # Helper function for movie image form
    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['image_form'] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'core:UpdateVote',
                    kwargs={
                        'movie_id': vote.movie.id,
                        'pk': vote.id
                    }
                )
            else:
                vote_form_url = reverse(
                    'core:CreateVote',
                    kwargs={
                        'movie_id': self.object.id
                    }
                )
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return movie_detail_url


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={
                'pk': movie_id
            }
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={
                'pk': movie_id
            }
        )
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                "Cannot change another user's vote"
            )
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(
            to=movie_detail_url
        )

core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>{{ object }}</h1>
<p class="lead">
{{ object.plot }}
</p>
  <p>Directed by {{ object.director }}</p>
  <p>Written by {{ object.writers.all|unordered_list }}</p>
  <h2>Actors</h2>
  <ul>
  {% for credit in object.role_set.all %}
    <li><a href="{% url 'core:PersonDetail' pk=credit.person.id %}">{{ credit.person }}: {{ credit.billing }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

{% block sidebar %}
  <div >
    This movie is rated:
    <span class="badge badge-primary" >
  {{ object.get_rating_display }}
  </span >
  </div >
  <div >
    <h2 >
      Score: {{ object.score|default_if_none:"TBD" }}
    </h2 >
  </div>
  <div>
    {% if vote_form %}
      <form
          method="post"
          action="{{ vote_form_url }}" >
        {% csrf_token %}
        {{ vote_form.as_p }}
        <button
            class="btn btn-primary" >
          Vote
        </button >
      </form >
    {% else %}
      <p >Log in to vote for this
        movie</p >
    {% endif %}
  </div >
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
    All Movies
{% endblock %}

{% block main %}
    <ul>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'core:MovieDetail' pk=movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ul>
    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="{% url 'core:MovieList' %}?page=1">
                        First
                    </a>
                </li>
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number}}">
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="{% url 'core:MovieList' %}?page={{ page_obj.number }}">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'core:MovieList' %}?page=last">
                        Last
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}
{% endblock %}

core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}
    <h1>{{ object }}</h1>
    <h2>Actor</h2>
    <ul>
        {% for role in object.role_set.all %}
            <li>
                <a href="{% url 'core:MovieDetail' role.movie.id %}">
                    {{ role.movie }}
                </a>:
                {{ role.name }}
            </li>
        {% endfor %}
    </ul>
    <ul>
        {% for movie in object.writing_credits.all %}
            <li>
                <a href="{% url 'core:MovieDetail' movie.id%}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}

    </ul>
    <h2>Director</h2>
    <ul>
        {% for movie in object.directed.all %}
            <li>
                <a href="{% url 'core:MovieDetail' movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/top_movies_list.html
{% extends 'base.html' %}

{% block title %}
    Top 10 Movies
{% endblock %}

{% block main %}
    <h1>Top 10 Movies</h1>
    <ol>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'core:MovieDetail' pk=movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}