core/urls.py
from django.urls import path
from .views import (
    MovieList,
    MovieDetail,
    CreateVote,
    UpdateVote,
    MovieImageUpload,
    TopMovies
)

app_name = 'core'

urlpatterns = [
    path(
        'movies',
        MovieList.as_view(),
        name='MovieList'
    ),
    path(
        'movie/<int:pk>',
        MovieDetail.as_view(),
        name='MovieDetail'
    ),
    path(
        'movie/<int:movie_id>/vote',
        CreateVote.as_view(),
        name='CreateVote'
    ),
    path(
        'movie/<int:movie_id>/vote/<int:pk>',
        UpdateVote.as_view(),
        name='UpdateVote'
    ),
    path(
        'movie/<int:movie_id>/image/upload',
        MovieImageUpload.as_view(),
        name='MovieImageUpload'
    ),
    path(
        'movie/top',
        TopMovies.as_view(),
        name="TopMovies"
    ),
]

myMDB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import core.urls
import user.urls

# Development setting for specifying upload path
MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
] + MEDIA_FILE_PATHS

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
            crossorigin="anonymous"
    >
    <title>
        {% block title %}
            myMDB
        {% endblock %}
    </title>
    <style>
        .mymdb-masthead {
            background-color: #EEEEEE;
            margin-bottom: 1em;
        }
    </style>
</head>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">
                MyMDB
            </div>
            <a class="nav-link" href="{% url 'core:MovieList' %}">
                Movies
            </a>
            <a class="nav-link" href="{% url 'core:TopMovies' %}">
                Top 10 Movies
            </a>
        </nav>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}

            {% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>